### ISSUE TITLE
Add release checklist test: "Racket Tests"

### ISSUE THREAD

**Issue by jackfirth** [samth/docker-racket-build#31]
Owned by Matthew Flatt. Command: `racket -l tests/racket/test`. Might overlap with some existing tests.

@samth Do you know more about the status of this?

**Comment by jackfirth** [comment]
After some testing, I ran into the issue described in the first item of #1: file tests fail in all dockerized installations. Calling this issue blocked on racket/racket#1870.

**Comment by samth** [comment]
Is that with 6.11 or with a snapshot? If the former, can you try with a
snapshot? I think this is an ipv6 problem that mflatt fixed.

**Comment by jackfirth** [comment]
Yes, this is with the 6.11.0.2 snapshot installer. Command was `docker-compose run racket-x86-test racket -e '(load (collection-file-path "file.rktl" "tests/racket"))'` and the last few lines of output were:

```
(#<procedure:directory-exists?> #<path:./x/y>) ==> #t
(#<procedure:directory-exists?> #<path:./x/y>) ==> #f
(#<procedure:directory-exists?> #<path:./x/y>) ==> #t
(#<procedure:directory-exists?> #<path:./x/y/z>) ==> #t
(#<procedure:directory-exists?> #<path:/var/tmp/check-make-15111454771511145477044/nonesuch/>) ==> #f
(make-directory* "z")  =e=> "make-directory: cannot make directory\n  path: /var/tmp/check-make-15111454771511145477044/nonesuch/z\n  system error: No such file or directory; errno=2"
(for ((v (in-directory sub))) v)  =e=> (values #<void>) BUT EXPECTED ERROR
(in-directory (#<path:/var/tmp/in-dir-tmp-dir688/sub>)) ==> (#<path:/var/tmp/in-dir-tmp-dir688/sub>)
(#<procedure:exn?> #(struct:exn:fail:filesystem:errno "a" #<continuation-mark-set> (10 . posix))) ==> #t
(exn:fail:filesystem:errno "a" (current-continuation-marks) 10)  =e=> "exn:fail:filesystem:errno: contract violation\n  expected: (cons/c exact-integer? (or/c 'posix 'windows 'gai))\n  given: 10"
(exn:fail:filesystem:errno "a" (current-continuation-marks) (quote (10 posix)))  =e=> "exn:fail:filesystem:errno: contract violation\n  expected: (cons/c exact-integer? (or/c 'posix 'windows 'gai))\n  given: '(10 posix)"
(exn:fail:filesystem:errno "a" (current-continuation-marks) (quote (10)))  =e=> "exn:fail:filesystem:errno: contract violation\n  expected: (cons/c exact-integer? (or/c 'posix 'windows 'gai))\n  given: '(10)"
(exn:fail:filesystem:errno "a" (current-continuation-marks) (quote #(10)))  =e=> "exn:fail:filesystem:errno: contract violation\n  expected: (cons/c exact-integer? (or/c 'posix 'windows 'gai))\n  given: '#(10)"
expected an error
```

**Comment by jackfirth** [comment]
It looks like these tests create directories in `/tmp`. I think this might require some Docker setup to specify that containers are allowed to make temporary files.

**Comment by samth** [comment]
Yes, I'm confident that they do that, so allowing it would be good.

**Comment by jackfirth** [comment]
Do you know what other filesystem mutations they perform? Wondering if there's other directories that need to be configured.

**Comment by samth** [comment]
I don't know. Probably even @mflatt would have to try to see.

**Comment by mflatt** [comment]
".gitignore" files will list some other things, including "foreign-test.so" and some package directories that are constructed by the the pkg tests.
